apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8501
      protocol: TCP
  selector:
    app: web
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-app
        image: web-app:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: MODEL_IP
          value: "10.100.82.151"
        - name: MODEL_PORT
          value: "8000"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30